import logging
from typing import Dict, Any, Optional, Tuple
from langchain_core.messages import SystemMessage, HumanMessage
from src.utils.llm import get_llm, invoke_with_retry
from src.core.models import ExecutionPlan, SubTask
from src.core.state import WorkflowState
from src.memory.manager import memory_manager

# Initialize module logger
logger = logging.getLogger(__name__)

SUPERVISOR_SYSTEM_PROMPT = """You are a task planning supervisor. Given a user request, you will create an execution plan in structured JSON format. You have the following specialists available:
- research: Can search the web for up-to-date information and compile relevant details. Use this for gathering data or news.
- data: Can process text/data and perform calculations (text-based, no external tools).
- writing: Can draft text, summaries, reports, emails. Use this to summarize findings or write reports.
- code: Can save text content to files. Use this ONLY for writing files/reports to disk.

Rules:
1. Break the task into concrete, independent subtasks where possible.
2. Assign each subtask to the most appropriate specialist based on their capabilities.
3. For searching or gathering web news, ALWAYS use research.
4. For writing summaries, formatting tables, or writing reports, ALWAYS use writing.
5. For saving the report or results to a file, ALWAYS use code.
6. Mark dependencies: if a subtask needs the output of another, list its ID in dependencies.
7. For each subtask, clearly describe the expected output type.
8. Include a critical path: sequence of subtask IDs that are sequential bottlenecks.
"""

def validate_plan(plan: ExecutionPlan) -> Tuple[bool, Optional[str]]:
    """Validates the structure, IDs, dependencies, and specialist assignments of an execution plan.

    Args:
        plan (ExecutionPlan): The execution plan generated by the LLM.

    Returns:
        Tuple[bool, Optional[str]]: A tuple containing:
            - A boolean indicating if the plan is valid.
            - A string describing the validation error if invalid, or None if valid.
    """
    subtask_ids = {st.id for st in plan.subtasks}
    
    # Check for duplicate IDs
    if len(subtask_ids) != len(plan.subtasks):
        logger.warning("Plan validation failed: Duplicate subtask IDs detected.")
        return False, "Duplicate subtask IDs found."
    
    # Check that all dependency IDs exist in plan
    for st in plan.subtasks:
        for dep_id in st.dependencies:
            if dep_id not in subtask_ids:
                err_msg = f"Subtask '{st.id}' depends on nonexistent ID '{dep_id}'."
                logger.warning(f"Plan validation failed: {err_msg}")
                return False, err_msg
    
    # Check critical path IDs exist
    for cp_id in plan.critical_path:
        if cp_id not in subtask_ids:
            err_msg = f"Critical path ID '{cp_id}' not found in subtasks."
            logger.warning(f"Plan validation failed: {err_msg}")
            return False, err_msg
    
    # Check that assigned_to is a valid specialist
    valid_specialists = {"research", "data", "writing", "code"}
    for st in plan.subtasks:
        if st.assigned_to not in valid_specialists:
            err_msg = f"Subtask '{st.id}' assigned to unknown specialist '{st.assigned_to}'."
            logger.warning(f"Plan validation failed: {err_msg}")
            return False, err_msg
            
    logger.info("Generated execution plan successfully validated.")
    return True, None


def supervisor_node(state: WorkflowState) -> Dict[str, Any]:
    """LangGraph node representing the supervisor planner.
    
    Generates a structured execution plan, retrieving past task execution
    records from long-term memory for semantic planning guidance.

    Args:
        state (WorkflowState): Current global graph state.

    Returns:
        Dict[str, Any]: State updates with the new plan and retry increment.
    """
    logger.info("Supervisor node: Initiating task planning execution.")
    llm = get_llm(temperature=0)
    structured_llm = llm.with_structured_output(ExecutionPlan)
    
    # Fetch similar past tasks from long-term memory
    user_request = state["user_request"]
    similar_tasks = memory_manager.get_context_for_planning(user_request)
    
    # Build context string from memory queries
    memory_context = ""
    if similar_tasks:
        memory_context = "Similar past tasks and their results:\n"
        for i, task in enumerate(similar_tasks):
            doc = task['document'][:150] + "..."   # 150 chars max
            memory_context += f"{i+1}. {doc}\n"
        logger.debug(f"Retrieved memory context context size: {len(memory_context)} characters")
    
    messages = [
        SystemMessage(content=SUPERVISOR_SYSTEM_PROMPT),
        HumanMessage(content=f"User request: {user_request}\n{memory_context}")
    ]
    
    if state.get("validation_errors"):
        logger.info(f"Supervisor plan generation retry due to errors: {state['validation_errors']}")
        feedback = HumanMessage(content=f"Previous plan had errors: {state['validation_errors']}. Please fix the plan.")
        messages.append(feedback)
    
    plan: ExecutionPlan = invoke_with_retry(structured_llm, messages)
    logger.info(f"Supervisor successfully generated execution plan: '{plan.overall_goal}'")
    return {
        "plan": plan, 
        "retry_count": state.get("retry_count", 0) + 1,
        "memory_context": memory_context
    }

def validation_node(state: WorkflowState) -> Dict[str, Any]:
    """LangGraph node representing the validation step.
    
    Evaluates the supervisor's execution plan structure.

    Args:
        state (WorkflowState): Current global graph state.

    Returns:
        Dict[str, Any]: State updates with validation errors (if any).
    """
    plan = state["plan"]
    if not plan:
        logger.error("Validation node executed but no plan was found in state.")
        return {"validation_errors": "No plan found to validate."}
        
    is_valid, error = validate_plan(plan)
    return {"validation_errors": error}